### ISSUE TITLE
[Add]add cyber security conf 

### ISSUE THREAD

**Issue by Qc-TX** [MLNLP-World/AI-Paper-Collector#104]
[
{
'name': 'SP2021',
'url': 'https://dblp.org/db/conf/sp/sp2021.html',
'source': 'dblp'
},
{
'name': 'sp2022',
'url': 'https://dblp.org/db/conf/sp/sp2022.html',
'source': 'dblp'
},
{
'name': 'ccs2021',
'url': 'https://dblp.org/db/conf/ccs2021/ccs2021.html',
'source': 'dblp'
},
{
'name': 'ccs2022',
'url': 'https://dblp.org/db/conf/ccs/ccs2022.html',
'source': 'dblp'
},
{
'name': 'ndss2021',
'url': 'https://dblp.org/db/conf/ndss/ndss2021.html',
'source': 'dblp'
},
{
'name': 'ndss2022',
'url': 'https://dblp.org/db/conf/ndss/ndss2022.html',
'source': 'dblp'
},
{
'name': 'ndss2023',
'url': 'https://dblp.org/db/conf/ndss/ndss2023.html',
'source': 'dblp'
},
]

**Comment by Doragd** [comment]
暂时还没有计划添加，非常抱歉~你可以fork这个项目
