### ISSUE TITLE
The schedule of required features

### ISSUE THREAD

**Issue by Doragd** [MLNLP-World/AI-Paper-Collector#27]
- [x] Add code links and paper links @LightChen233 
- [x] The optimization of front-end (need more details) @beiyuouo
- [x] search by sessions @SivilTaram
- [x] search in the last search results @beiyuouo
- [x] Refactor the current workflow @Doragd 
- [ ] fix: search ACL and return NAACL/ACL
- [x] format: year, conf, ...
- [x] provide the list of confs before search
- [ ] multi-process crawl

**Comment by SivilTaram** [comment]
@Doragd I'd love to develop the feature of session-based search.

**Comment by Doragd** [comment]
out of date.
