### ISSUE TITLE
[Add] AISTAT, VLDB, COLT

### ISSUE THREAD

**Issue by yinxiangshi** [MLNLP-World/AI-Paper-Collector#32]
[
{
'name':'JMLR2022',
'url':'https://dblp.org/db/journals/jmlr/jmlr22.html',
'source': 'dblp',
},
{
'name':'JMLR2021',
'url':'https://dblp.org/db/journals/jmlr/jmlr21.html',
'source': 'dblp',
},
{
'name':'JMLR2020',
'url':'https://dblp.org/db/journals/jmlr/jmlr20.html',
'source': 'dblp',
},
{
'name':'JMLR2019',
'url':'https://dblp.org/db/journals/jmlr/jmlr19.html',
'source': 'dblp'
},
{
'name':'VLDB2019',
'url':'https://dblp.org/db/journals/pvldb/pvldb13.html',
'source': 'dblp',
},
{
'name':'VLDB2020',
'url':'https://dblp.org/db/journals/pvldb/pvldb14.html',
'source': 'dblp',
},
{
'name':'VLDB2021',
'url':'https://dblp.org/db/journals/pvldb/pvldb15.html',
'source': 'dblp',
},
]

**Comment by yinxiangshi** [comment]
Thanks for your script!

**Comment by yinxiangshi** [comment]
Also,
[
{
'name':'Journal of Machine Learning Research',
'url':'https://www.jmlr.org/',
},
{
'name':'Transactions on Machine Learning Research',
'url':'https://www.jmlr.org/tmlr/',
},
]

**Comment by Doragd** [comment]
sorry, till now, only support "dblp | nips | icir | acl"

**Comment by yinxiangshi** [comment]
@Doragd Here is the renewal link:
[
{
'name':'Journal of Machine Learning Research',
'url':'https://dblp.org/db/journals/jmlr/index.html',
},
{
'name':'international Conference on Artificial Intelligence and Statistics',
'url':'https://dblp.org/db/conf/aistats/index.html',
},
{
'name':'Very Large Data Bases (VLDB) Conference',
'url':'https://dblp.org/db/conf/vldb/index.html',
},
{
'name':'Annual Conference Computational Learning Theory (COLT)',
'url':'https://dblp.org/db/conf/colt/index.html',
},
]

**Comment by Doragd** [comment]
@yinxiangshi I have fixed the issue. Please follow the format.

**Comment by Doragd** [comment]
@yinxiangshi You can add more confs, like COLT, AISTATS...

**Comment by yinxiangshi** [comment]
@Doragd You mean to let me add the COLT AISTAT by pr? Got u.

**Comment by Doragd** [comment]
@yinxiangshi raise a new issue. Please follow the format: https://github.com/MLNLP-World/AI-Paper-Collector/issues/10

**Comment by yinxiangshi** [comment]
@Doragd Sry I didn't notice the user guide about how to add new conf, gotcha.

**Comment by Doragd** [comment]
@yinxiangshi Don't mind. You can try again. I will check it.
