### ISSUE TITLE
[Add] AISTAT, COLT

### ISSUE THREAD

**Issue by yinxiangshi** [MLNLP-World/AI-Paper-Collector#33]
[
{
'name':'COLT2021',
'url':'https://dblp.org/db/conf/colt/colt2021.html',
'source':'dblp',
},
{
'name':'COLT2020',
'url':'https://dblp.org/db/conf/colt/colt2020.html',
'source':'dblp',
},
{
'name':'COLT2019',
'url':'https://dblp.org/db/conf/colt/colt2019.html',
'source':'dblp',
},
{
'name':'AISTATS2021',
'url':'https://dblp.org/db/conf/aistats/aistats2021.html',
'source':'dblp',
},
{
'name':'AISTATS2020',
'url':'https://dblp.org/db/conf/aistats/aistats2020.html',
'source':'dblp',
},
{
'name':'AISTATS2019',
'url':'https://dblp.org/db/conf/aistats/aistats2019.html',
'source':'dblp',
},
]

**Comment by Doragd** [comment]
Added.
