### ISSUE TITLE
[Feature]能不能按照引用多少或者其他什么的排序啊，或者多显示一些信息呢

### ISSUE THREAD

**Issue by Dhuzi96** [MLNLP-World/AI-Paper-Collector#34]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Comment by Dhuzi96** [comment]
只看到文章的名字感觉信息量太少了啊

**Comment by Doragd** [comment]
我们后续会添加更多信息，谢谢你的建议，功能正在开发中
