### ISSUE TITLE
[Feature request] Search for specific year 

### ISSUE THREAD

**Issue by Sqhttwl** [MLNLP-World/AI-Paper-Collector#41]
**Question**
想问下支持年份搜索吗，比如只下载ACM MM2021的15篇文章

**Screenshots**

**Desktop (please complete the following information):**

- OS: [Ubuntu]
- Version [20.04]

**Comment by beiyuouo** [comment]
现在在 `Advanced setting` 里面支持了具体年份的搜索，可以来试一下~
https://ai-paper-collector.vercel.app/
