### ISSUE TITLE
[BUG] Some conferences disappear?

### ISSUE THREAD

**Issue by canyuchen** [MLNLP-World/AI-Paper-Collector#63]
**Describe the bug**

Some conferences disappear?

![image](https://user-images.githubusercontent.com/21056130/193434409-10829a89-14bd-48fe-b869-6f9ced9b91e7.png)

**Comment by Doragd** [comment]
不好意思，网站正在升级，今天上午就可以完成

**Comment by Doragd** [comment]
已恢复
