### ISSUE TITLE
[Question] Any plan to add the conferences before 2018?

### ISSUE THREAD

**Issue by canyuchen** [MLNLP-World/AI-Paper-Collector#68]
**Question**
Seemingly the current searched results are after 2018. Any plan to add the conferences before 2018? Thanks for the hard work!

**Comment by Doragd** [comment]
谢谢您的关注。
暂时没有计划📱。
原因在于我们设计这个系统的初衷并不是做一个大而全的系统，而是尽量减少人们检索和筛选优质论文的时间成本。
如果范围过大，人们从中筛选论文的成本又会增加。
欢迎讨论您的想法。
