### ISSUE TITLE
[Feature] Suggestion: grouping the conferences into different fields

### ISSUE THREAD

**Issue by canyuchen** [MLNLP-World/AI-Paper-Collector#73]
Hi, I suggest adding a feature to group the conferences into different fields like the csranking.org website. So it is more convenient to search papers in a specific field because we do not need to select every conference in the specific field for each search. Hope you could take this suggestion into consideration. Love this tool. Thanks!

https://csrankings.org/#/index?all&us

<img width="333" alt="image" src="https://user-images.githubusercontent.com/21056130/198904912-e9562f54-db87-42ea-96be-1a8a5b205a36.png">

**Comment by Doragd** [comment]
Sounds Great! I will add this feature soon with the category of csranking.
