### ISSUE TITLE
[Feature] Suggestion: Besides the normal "search" tab, adding an "advanced search" tab

### ISSUE THREAD

**Issue by canyuchen** [MLNLP-World/AI-Paper-Collector#75]
Sometimes the normal search results are too many. I suggest adding an "advanced search" tab. So I can use **regular expression** as the input to narrow down the search scope. Thanks!

**Comment by canyuchen** [comment]
For example, if I want to search the papers with titles containing both "effective" and "prompt", I can utilize regular expressions to achieve it.

**Comment by Doragd** [comment]
To be frank, it is really useful to search with regular expressions. However, I am busy with my graduation work. Do you have any interest to join us to develop this feature? contact me via my email: guodun.li#gmail.com.

**Comment by canyuchen** [comment]
Yes, I am glad to join! I will contact you via email
