### ISSUE TITLE
[BUG] Search papers by author

### ISSUE THREAD

**Issue by LingyvKong** [MLNLP-World/AI-Paper-Collector#76]
**Describe the bug**
在 Advanced Setting - Specific Author 中搜索作者，会包含一些错误的结果，比如搜索“Ming Li”，除了正确的结果外，还会包含错误的结果如“Xiaoming Li”，“Xiaoming Liu” （名字是我瞎说的，仅作错误示意）

**Expected behavior**
希望只包含正确的结果，如果可以将搜索作者高亮显示就更好啦~💕

**Comment by Doragd** [comment]
fixed.
