### ISSUE TITLE
app方式完全用不了，什么时候能修复？

### ISSUE THREAD

**Issue by wgfrhebnr** [MLNLP-World/AI-Paper-Collector#79]
**Question**
Add your question here
app方式完全用不了，什么时候能修复？
**Screenshots**

**Desktop (please complete the following information):**

- OS: [e.g. Ubuntu]
- Version [e.g. 0.1.7]

**Comment by Doragd** [comment]
抱歉造成不便。
目前请尽量使用web版本。
