### ISSUE TITLE
[Feature] Web可以增加分页吗？目前版本有点卡

### ISSUE THREAD

**Issue by shliujing** [MLNLP-World/AI-Paper-Collector#81]
**Is your feature request related to a problem? Please describe.**
1. 所有检索结果都在1个页，导致页面数据过多，很卡，不能点击
2. 勾选的会议，刷新后又是全选。得重新设置

**Describe the solution you'd like**
1. 增加分页功能，默认显示10条
2. 在设置里可以设置单页显示多少条，或显示所有（即原版本）
4. 记住勾选设置项，本地存储，刷新后保持。强刷页面才刷掉cache

**Comment by Doragd** [comment]
谢谢前辈的建议~不知道您是否有兴趣加入一起开发~我对前端其实不是太熟qwq

**Comment by shliujing** [comment]
哈哈，看到你在其他issue的留言了，忙着毕业。奈何我也是~
好的，等我后面空些，抽空研究一下。预计1-2天可以搞定。

**Comment by Doragd** [comment]
方便的话，可以加我微信后续联系：gordon_lgd
