### ISSUE TITLE
增加期刊IJCV的论文

### ISSUE THREAD

**Issue by wgfrhebnr** [MLNLP-World/AI-Paper-Collector#86]
[
{
'name':'IJCV2020',
'url':'https://dblp.uni-trier.de/db/journals/ijcv/ijcv128.html',
'source':'dblp',
},
{
'name':'IJCV2021',
'url':'https://dblp.uni-trier.de/db/journals/ijcv/ijcv129.html',
'source':'dblp',
},
{
'name':'IJCV2022',
'url':'https://dblp.uni-trier.de/db/journals/ijcv/ijcv130.html',
'source':'dblp',
},
]

**Comment by Doragd** [comment]
建议查看closed issue的示例，来源填写为dblp的网址，不是springer，另外，[]是placeholder

**Comment by Doragd** [comment]
@wgfrhebnr 已修改格式，已添加，请访问：http://47.101.133.186/
