### ISSUE TITLE
增加期刊TNNLS

### ISSUE THREAD

**Issue by wgfrhebnr** [MLNLP-World/AI-Paper-Collector#87]
[
{
'name':'[TNNLS]',
'url':'[https://dblp.org/db/journals/tnn/index.html]',
'source':'[dblp]',
},
]

**Comment by Doragd** [comment]
请认真查看之前的issue，修改好格式。

**Comment by wgfrhebnr** [comment]
抱歉哈，由于我第一次去增加期刊，会议，有些不太熟悉，难免会犯错



| |
***@***.***
|
|
***@***.***
|




---- 回复的原邮件 ----
| 发件人 | Gordon ***@***.***> |
| 日期 | 2023年02月06日 12:06 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [MLNLP-World/AI-Paper-Collector] 增加期刊TNNLS (Issue #87) |

请认真查看之前的issue，修改好格式。

**Comment by Doragd** [comment]
你这是第三次了。我上一个issue都建议你查看旧的issue了
https://github.com/MLNLP-World/AI-Paper-Collector/issues/86#issuecomment-1418462912

**Comment by wgfrhebnr** [comment]
嗯嗯，在看了。主要是dblp网站地址不太熟悉，我在里面搜索到期刊名字，就把网址链接复制上去了



| |
***@***.***
|
|
***@***.***
|




---- 回复的原邮件 ----
| 发件人 | Gordon ***@***.***> |
| 日期 | 2023年02月06日 12:11 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [MLNLP-World/AI-Paper-Collector] 增加期刊TNNLS (Issue #87) |

你这是第三次了。我上一个issue都建议你查看旧的issue了
#86 (comment)

**Comment by wgfrhebnr** [comment]
让我摸索一下，应该就很快知道如何适应了



| |
***@***.***
|
|
***@***.***
|




---- 回复的原邮件 ----
| 发件人 | Gordon ***@***.***> |
| 日期 | 2023年02月06日 12:11 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [MLNLP-World/AI-Paper-Collector] 增加期刊TNNLS (Issue #87) |

你这是第三次了。我上一个issue都建议你查看旧的issue了
#86 (comment)
