### ISSUE TITLE
增加TNNLS

### ISSUE THREAD

**Issue by wgfrhebnr** [MLNLP-World/AI-Paper-Collector#88]
[
{
'name': 'TNNLS',
'url': 'https://dblp.org/db/journals/tnn/index.html',
'source': 'dblp'
},
]

**Comment by Doragd** [comment]
....建议好好查看之前的IJCV issue。。。你这年份没有，具体年份的网址也没有。。

**Comment by wgfrhebnr** [comment]
嗯嗯，我在摸索，再试一两次我应该就会了



| |
***@***.***
|
|
***@***.***
|




---- 回复的原邮件 ----
| 发件人 | Gordon ***@***.***> |
| 日期 | 2023年02月06日 12:17 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [MLNLP-World/AI-Paper-Collector] 增加TNNLS (Issue #88) |

....建议好好查看之前的IJCV issue。。。你这年份没有，具体年份的网址也没有。。

**Comment by wgfrhebnr** [comment]
对了，请问期刊可以添加多少年的论文，最近三年还是最近五年？



| |
***@***.***
|
|
***@***.***
|




---- 回复的原邮件 ----
| 发件人 | Gordon ***@***.***> |
| 日期 | 2023年02月06日 12:17 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [MLNLP-World/AI-Paper-Collector] 增加TNNLS (Issue #88) |

....建议好好查看之前的IJCV issue。。。你这年份没有，具体年份的网址也没有。。

**Comment by Doragd** [comment]
请联系邮箱: guodun.li#gmail.com。不要在已关闭的issue中讨论。
