### ISSUE TITLE
[Feature] Some UI advices

### ISSUE THREAD

**Issue by timelic** [MLNLP-World/AI-Paper-Collector#93]
**Is your feature request related to a problem? Please describe.**

很好网站，❤️来自China。

下面是几个小建议。
- 搜索结果页的两侧的筛选栏，可以考虑换个样式。现在有点像浮动广告。
- 或许可以直接在搜索结果页的每一个结果的标题下面，直接显示摘要和引用量。
- 搜索结果右上角的删除按钮是没有必要的，看起来并不会影响下次的搜索结果。
- 能不能添加一个Cite按钮？可以一键引用文献，就像谷歌学术那样。

**Comment by Doragd** [comment]
1. 谢谢建议，我们会考虑
2. 显示摘要这件事我也比较推荐采用非悬浮窗口的形式。至于引用，因为引用数据更新频率和权威性问题，暂时不显示
3. 我们的目的是为大家提供更快的筛选论文的方式，然后导出成论文列表。提供删除按钮方便大家删掉不想看的论文。这样导出列表里面不会包括。
4. Bibtex也存在权威性问题

**Comment by yang20000825** [comment]
网站做的非常好，非常方便。就是今天更新以后好像没有了在搜索结果中再次搜索的功能？

**Comment by timelic** [comment]
感谢耐心回复⛽️
