### ISSUE TITLE
[Question] Could you add some community standards

### ISSUE THREAD

**Issue by UNICKCHENG** [MLNLP-World/AI-Paper-Collector#95]
**Question**

Hey, there, could you add some community standards ?

https://github.com/MLNLP-World/AI-Paper-Collector/community

- Adding guidelines for repository contributors：
https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/setting-guidelines-for-repository-contributors

- Adding repository licenses：
https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository#disclaimer

**Desktop (please complete the following information):**

- OS: [e.g. Ubuntu]
- Version [e.g. 0.1.7]

**Comment by Doragd** [comment]
Many thanks. I will follow the checklist
