### ISSUE TITLE
[Add] SIGMOD

### ISSUE THREAD

**Issue by UntaggedRui** [MLNLP-World/AI-Paper-Collector#97]
[
{
'name':'SIGMOD2022',
'url':'https://dblp.org/db/conf/sigmod/sigmod2022.html',
'source':'dblp',
},
{
'name':'SIGMOD2021',
'url':'https://dblp.org/db/conf/sigmod/sigmod2021.html',
'source':'dblp',
},
{
'name':'SIGMOD2020',
'url':'https://dblp.org/db/conf/sigmod/sigmod2020.html',
'source':'dblp',
},
{
'name':'SIGMOD2019',
'url':'https://dblp.org/db/conf/sigmod/sigmod2019.html',
'source':'dblp',
},
]

**Comment by Doragd** [comment]
added
