### ISSUE TITLE
[Add] FAST

### ISSUE THREAD

**Issue by UntaggedRui** [MLNLP-World/AI-Paper-Collector#98]
[
{
'name':'fast2023',
'url':'https://dblp.org/db/conf/fast/fast2023.html',
'source':'dblp',
},
{
'name':'fast2022',
'url':'https://dblp.org/db/conf/fast/fast2022.html',
'source':'dblp',
},
{
'name':'fast2021',
'url':'https://dblp.org/db/conf/fast/fast2021.html',
'source':'dblp',
},
{
'name':'fast2020',
'url':'https://dblp.org/db/conf/fast/fast2020.html',
'source':'dblp',
},
{
'name':'fast2019',
'url':'https://dblp.org/db/conf/fast/fast2019.html',
'source':'dblp',
},

]

**Comment by Doragd** [comment]
added
